### ISSUE TITLE
Can not run under Java 8

### ISSUE THREAD

**Issue by kppgs** [DevComPack/setupmaker#1]
I got an error:
![image](https://cloud.githubusercontent.com/assets/22025552/18511153/831a848a-7a82-11e6-93b2-722661fbea45.png)

Although I can run the jar file directly

**Comment by saidelimam** [comment]
Apache Pivot still has some compatibility problems with Java 8, so it is preferred to use JDK 7 until it is fixed.

Thx for submitting this issue.

**Comment by nubbix** [comment]
Any news to this now Said, been almost a year? Don't you believe they fixed the compatibility issue by now?

**Comment by saidelimam** [comment]
Yes indeed it looks like they've released a fix to it, I just looked it up. I'll try to make a new fix release in the coming days :)

**Comment by saidelimam** [comment]
fixed for version 1.3

**Comment by nubbix** [comment]
That is just awesome Said :) Thank you
