### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by ghost** [DevComPack/setupmaker#3]
Hi,

I don't understand if I upload the Java installer anyone with Mac, Linux or Windows can install it? Just with that file? Do they need Java installed to run it?

**Comment by saidelimam** [comment]
Hello,

Yes the Java installer can be ran from any platform as long as it contains Java installed. You may also want to package the Jar file into an executable depending on the targeted OS so it won't need Java.

You can use this [Google Group](https://groups.google.com/forum/#!forum/dcp-setup-makers) for future questions ;)
