### ISSUE TITLE
Custom laguage option isn't working

### ISSUE THREAD

**Issue by danieltartarottisobrosa** [DevComPack/setupmaker#4]
I am trying to define a custom language, but the iso3 country code isn't reconized.

![bra-langpack](https://cloud.githubusercontent.com/assets/3154766/19189560/09fa1e86-8c6f-11e6-806b-0eb0ed23c906.png)

![error](https://cloud.githubusercontent.com/assets/3154766/19189627/643697c6-8c6f-11e6-988a-68cd056551b2.png)

In order to solve the problem, I tried to add a `"bra"` in the `settings.json > codes > iso3` property, but all stay the same.

![iso3-country-codes](https://cloud.githubusercontent.com/assets/3154766/19189559/09fa0de2-8c6f-11e6-8cff-94a8a8c53767.png)

I am sure that the problem is the iso3 code, because if I use a different one of those codes shown in the list below (except the `bra` code witch I've included), the problem appears.

**Comment by danieltartarottisobrosa** [comment]
I tried to use the `POR` country code (instead `BRA`) and the brazilian flag was shown to me!!! It's wrong. This is the Portugal code.

**Comment by danieltartarottisobrosa** [comment]
As this problem is caused by IzPack, I will close this issue.

**Comment by saidelimam** [comment]
Yes indeed it's Izpack related, however this is not an issue. Izpack is waiting for a 'language' iso code and not a country one, and Brazil's language is Portuguese ;)
