### ISSUE TITLE
JRE in package

### ISSUE THREAD

**Issue by ermoschink** [DevComPack/setupmaker#8]
Can I add JRE to the installer package ?

**Comment by saidelimam** [comment]
Can you explain your need more please?

**Comment by ermoschink** [comment]
I want to generate a  installer package which bundles JRE specified by me.
PS:
I'm sorry, it's really bad with English.

**Comment by saidelimam** [comment]
Oh ok, for this you need to use launch4j to bundle a JRE with your generated jar file
https://sourceforge.net/projects/launch4j/

It is planned to integrate it with DCP but for now you must use it separately :)

**Comment by ermoschink** [comment]
Thank you!
